<?php
namespace Database\Seeders;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
class OrderDetailSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::statement('SET FOREIGN_KEY_CHECKS = 0');
        DB::table('order_details')->truncate();
        DB::table('order_details')->insert([
            [
                'orderId'=>9,
                'productId'=>9,
                'quantity'=>1,
                'amount'=>20000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>8,
                'productId'=>8,
                'quantity'=>2,
                'amount'=>30000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>7,
                'productId'=>7,
                'quantity'=>3,
                'amount'=>40000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>6,
                'productId'=>9,
                'quantity'=>4,
                'amount'=>50000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>5,
                'productId'=>8,
                'quantity'=>5,
                'amount'=>60000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>4,
                'productId'=>9,
                'quantity'=>6,
                'amount'=>70000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>3,
                'productId'=>6,
                'quantity'=>7,
                'amount'=>80000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>2,
                'productId'=>7,
                'quantity'=>8,
                'amount'=>90000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>1,
                'productId'=>2,
                'quantity'=>9,
                'amount'=>100000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>2,
                'productId'=>3,
                'quantity'=>10,
                'amount'=>110000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>3,
                'productId'=>4,
                'quantity'=>11,
                'amount'=>120000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>3,
                'productId'=>4,
                'quantity'=>12,
                'amount'=>130000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>4,
                'productId'=>5,
                'quantity'=>13,
                'amount'=>140000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>5,
                'productId'=>6,
                'quantity'=>14,
                'amount'=>150000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>7,
                'productId'=>8,
                'quantity'=>15,
                'amount'=>160000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>8,
                'productId'=>9,
                'quantity'=>16,
                'amount'=>170000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>9,
                'productId'=>8,
                'quantity'=>17,
                'amount'=>180000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>9,
                'productId'=>9,
                'quantity'=>18,
                'amount'=>190000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>8,
                'productId'=>9,
                'quantity'=>19,
                'amount'=>200000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>7,
                'productId'=>9,
                'quantity'=>20,
                'amount'=>210000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>6,
                'productId'=>9,
                'quantity'=>21,
                'amount'=>220000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>5,
                'productId'=>9,
                'quantity'=>22,
                'amount'=>230000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>4,
                'productId'=>9,
                'quantity'=>23,
                'amount'=>240000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>3,
                'productId'=>9,
                'quantity'=>24,
                'amount'=>250000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>2,
                'productId'=>9,
                'quantity'=>25,
                'amount'=>260000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>1,
                'productId'=>9,
                'quantity'=>26,
                'amount'=>270000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>9,
                'productId'=>8,
                'quantity'=>27,
                'amount'=>280000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>9,
                'productId'=>7,
                'quantity'=>28,
                'amount'=>290000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>9,
                'productId'=>7,
                'quantity'=>29,
                'amount'=>30000,
                'created_at'=>Carbon::now()->addDays(1)
            ],[
                'orderId'=>9,
                'productId'=>6,
                'quantity'=>30,
                'amount'=>310000,
                'created_at'=>Carbon::now()->addDays(1)
            ]
        ]);
    }
}
